import {
	getHtmlPage,
} from '../src/html/html.js';

describe('getHtmlPage', () => {
	it('returns a html page with the given content', () => {
		expect(getHtmlPage('', '', [], {})).toBe([
			'<html lang="en">',
			'<head>',
			'<meta charset="UTF-8">',
			'<meta name="viewport" content="width=device-width, initial-scale=1.0">',
			'<meta http-equiv="X-UA-Compatible" content="ie=edge">',
			'<title>Oracle Health Dashboard</title>',
			'<meta name="description" content="Oracle Health Dashboard">',
			'<style>',
			'* {',
			'	font-family: Arial, Helvetica, sans-serif;',
			'}',
			'',
			'.green {',
			'	color:green;',
			'}',
			'',
			'.red {',
			'	color: red;',
			'}',
			'',
			'.metrics-enclosure {',
			'	height: 200px;',
			'	overflow: auto;',
			'	margin-top: 4px;',
			'	margin-bottom: 4px;',
			'}',
			'',
			'.metrics {',
			'	display: grid;',
			'	grid-template-columns: max-content max-content;',
			'	grid-row-gap: 4px;',
			'	grid-column-gap: 10px;',
			'	font-size: x-small;',
			'}',
			'',
			'.timestamp {',
			'	margin-left: 10px;',
			'	font-size: small;',
			'}',
			'',
			'</style>',
			'</head>',
			'<body>',
			'</body>',
			'</html>',
		].join('\n'));

		expect(getHtmlPage('title', 'content', [], {})).toBe([
			'<html lang="en">',
			'<head>',
			'<meta charset="UTF-8">',
			'<meta name="viewport" content="width=device-width, initial-scale=1.0">',
			'<meta http-equiv="X-UA-Compatible" content="ie=edge">',
			'<title>Oracle Health Dashboard - title</title>',
			'<meta name="description" content="Oracle Health Dashboard - title">',
			'<style>',
			'* {',
			'	font-family: Arial, Helvetica, sans-serif;',
			'}',
			'',
			'.green {',
			'	color:green;',
			'}',
			'',
			'.red {',
			'	color: red;',
			'}',
			'',
			'.metrics-enclosure {',
			'	height: 200px;',
			'	overflow: auto;',
			'	margin-top: 4px;',
			'	margin-bottom: 4px;',
			'}',
			'',
			'.metrics {',
			'	display: grid;',
			'	grid-template-columns: max-content max-content;',
			'	grid-row-gap: 4px;',
			'	grid-column-gap: 10px;',
			'	font-size: x-small;',
			'}',
			'',
			'.timestamp {',
			'	margin-left: 10px;',
			'	font-size: small;',
			'}',
			'',
			'</style>',
			'</head>',
			'<body>',
			'content',
			'</body>',
			'</html>',
		].join('\n'));
	});
});
